ALTER TABLE B DROP CONSTRAINT FK_B_C_ID
ALTER TABLE C DROP CONSTRAINT FK_C_C_D_ID
ALTER TABLE D DROP CONSTRAINT FK_D_C_D_ID
ALTER TABLE A DROP CONSTRAINT FK_A_E_ID
DROP TABLE C_D
DROP TABLE B
DROP TABLE C
DROP TABLE D
DROP TABLE E
DROP TABLE A
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
